log:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    ports:
        - "9200:9200"
        - "9300:9300"
    environment:
        - "http.host=0.0.0.0"
        - "transport.host=127.0.0.1"
        - "cluter=log"
        - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
       
    restart: always
        
kibana:
    image: kibana:5.2
    ports:
        - "5601:5601"
    links:
        - log:elasticsearch
    restart: always
        
curator_with_cron:
    image: eldersoss/curator-docker:2.0.0-beta0001
    command: "--host elasticsearch --port 9200 delete_indices --filter_list '{\"filtertype\":\"age\", \"source\":\"name\",\"direction\":\"older\", \"timestring\":\"%Y.%m.%d\", \"unit\":\"days\", \"unit_count\":\"10\" }'"
    links:
        - log:elasticsearch
    restart: always
    