version: '2'

services:
    elasticsearch:
        container_name: elasticsearch-log
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - cluster.name=log
            - bootstrap.memory_lock=true  # Disables swapping for performance and node stability.
            - "ES_JAVA_OPTS=-Xms4g -Xmx4g" # environment variable to set heap size
            - "discovery.zen.minimum_master_nodes=1"
        ulimits: # https://www.elastic.co/guide/en/elasticsearch/reference/6.1/docker.html
            memlock:
                soft: -1
                hard: -1
        volumes:
            - eslogdata:/usr/share/elasticsearch-log/data
        networks:
            - log-network
        restart: always

    kibana:
        container_name: kibana-log
        image: docker.elastic.co/kibana/kibana-oss:6.1.1
        ports:
            - "5601:5601"
        networks:
            - log-network
        restart: always

    curator_with_cron:
        container_name: curator-log
        image: eldersoss/curator-docker:3.0.0-beta0001
        command: --host elasticsearch-log --port 9200 delete_indices --filter_list \'{\"filtertype\":\"age\",\"source\":\"name\",\"direction\":\"older\",\"timestring\":\"%Y.%m.%d\",\"unit\":\"days\",\"unit_count\":\"10\"}\'
        networks:
            - log-network    
        restart: always

volumes:
    eslogdata:

networks:
  log-network:
    driver: bridge